//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATBGEBot.AppAudit {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GPJ_AppAuditSoap", Namespace="https://gpjws.gpjco.com/GPJ_AppAudit")]
    public partial class GPJ_AppAudit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveUserDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppWishListLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppWishListCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppWishListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseAppWishItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAppWishItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeqIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppUsageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppSupportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppSupportDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppSupportByMonthOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GPJ_AppAudit() {
            this.Url = global::ATBGEBot.Properties.Settings.Default.ATBGEBot_AppAudit_GPJ_AppAudit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveUserDataCompletedEventHandler SaveUserDataCompleted;
        
        /// <remarks/>
        public event AppWishListLikeCompletedEventHandler AppWishListLikeCompleted;
        
        /// <remarks/>
        public event GetAppWishListCountCompletedEventHandler GetAppWishListCountCompleted;
        
        /// <remarks/>
        public event GetAppWishListCompletedEventHandler GetAppWishListCompleted;
        
        /// <remarks/>
        public event CloseAppWishItemCompletedEventHandler CloseAppWishItemCompleted;
        
        /// <remarks/>
        public event SaveAppWishItemCompletedEventHandler SaveAppWishItemCompleted;
        
        /// <remarks/>
        public event GetSeqIdCompletedEventHandler GetSeqIdCompleted;
        
        /// <remarks/>
        public event GetAppUsageCompletedEventHandler GetAppUsageCompleted;
        
        /// <remarks/>
        public event GetAppSupportCompletedEventHandler GetAppSupportCompleted;
        
        /// <remarks/>
        public event GetAppSupportDetailsCompletedEventHandler GetAppSupportDetailsCompleted;
        
        /// <remarks/>
        public event GetAppSupportByMonthCompletedEventHandler GetAppSupportByMonthCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/SaveUserData", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveUserData(string pUserName, string pUserDomain, string pMachineName, string pOSVersion, string pOSPlatform, int pOSMajor, int pOSMinor, int pOSBit, string pAppName, string pAppVersion, string pUserZone, string[] pENVIRONMENT) {
            object[] results = this.Invoke("SaveUserData", new object[] {
                        pUserName,
                        pUserDomain,
                        pMachineName,
                        pOSVersion,
                        pOSPlatform,
                        pOSMajor,
                        pOSMinor,
                        pOSBit,
                        pAppName,
                        pAppVersion,
                        pUserZone,
                        pENVIRONMENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUserDataAsync(string pUserName, string pUserDomain, string pMachineName, string pOSVersion, string pOSPlatform, int pOSMajor, int pOSMinor, int pOSBit, string pAppName, string pAppVersion, string pUserZone, string[] pENVIRONMENT) {
            this.SaveUserDataAsync(pUserName, pUserDomain, pMachineName, pOSVersion, pOSPlatform, pOSMajor, pOSMinor, pOSBit, pAppName, pAppVersion, pUserZone, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void SaveUserDataAsync(string pUserName, string pUserDomain, string pMachineName, string pOSVersion, string pOSPlatform, int pOSMajor, int pOSMinor, int pOSBit, string pAppName, string pAppVersion, string pUserZone, string[] pENVIRONMENT, object userState) {
            if ((this.SaveUserDataOperationCompleted == null)) {
                this.SaveUserDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUserDataOperationCompleted);
            }
            this.InvokeAsync("SaveUserData", new object[] {
                        pUserName,
                        pUserDomain,
                        pMachineName,
                        pOSVersion,
                        pOSPlatform,
                        pOSMajor,
                        pOSMinor,
                        pOSBit,
                        pAppName,
                        pAppVersion,
                        pUserZone,
                        pENVIRONMENT}, this.SaveUserDataOperationCompleted, userState);
        }
        
        private void OnSaveUserDataOperationCompleted(object arg) {
            if ((this.SaveUserDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUserDataCompleted(this, new SaveUserDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/AppWishListLike", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AppWishListLike(int pAppID, long pWishID, string[] pENVIRONMENT) {
            object[] results = this.Invoke("AppWishListLike", new object[] {
                        pAppID,
                        pWishID,
                        pENVIRONMENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AppWishListLikeAsync(int pAppID, long pWishID, string[] pENVIRONMENT) {
            this.AppWishListLikeAsync(pAppID, pWishID, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void AppWishListLikeAsync(int pAppID, long pWishID, string[] pENVIRONMENT, object userState) {
            if ((this.AppWishListLikeOperationCompleted == null)) {
                this.AppWishListLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppWishListLikeOperationCompleted);
            }
            this.InvokeAsync("AppWishListLike", new object[] {
                        pAppID,
                        pWishID,
                        pENVIRONMENT}, this.AppWishListLikeOperationCompleted, userState);
        }
        
        private void OnAppWishListLikeOperationCompleted(object arg) {
            if ((this.AppWishListLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppWishListLikeCompleted(this, new AppWishListLikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppWishListCount", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAppWishListCount(int pAppID, string[] pENVIRONMENT) {
            object[] results = this.Invoke("GetAppWishListCount", new object[] {
                        pAppID,
                        pENVIRONMENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppWishListCountAsync(int pAppID, string[] pENVIRONMENT) {
            this.GetAppWishListCountAsync(pAppID, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void GetAppWishListCountAsync(int pAppID, string[] pENVIRONMENT, object userState) {
            if ((this.GetAppWishListCountOperationCompleted == null)) {
                this.GetAppWishListCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppWishListCountOperationCompleted);
            }
            this.InvokeAsync("GetAppWishListCount", new object[] {
                        pAppID,
                        pENVIRONMENT}, this.GetAppWishListCountOperationCompleted, userState);
        }
        
        private void OnGetAppWishListCountOperationCompleted(object arg) {
            if ((this.GetAppWishListCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppWishListCountCompleted(this, new GetAppWishListCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppWishList", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppWishList(int pAppID, string[] pENVIRONMENT) {
            object[] results = this.Invoke("GetAppWishList", new object[] {
                        pAppID,
                        pENVIRONMENT});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppWishListAsync(int pAppID, string[] pENVIRONMENT) {
            this.GetAppWishListAsync(pAppID, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void GetAppWishListAsync(int pAppID, string[] pENVIRONMENT, object userState) {
            if ((this.GetAppWishListOperationCompleted == null)) {
                this.GetAppWishListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppWishListOperationCompleted);
            }
            this.InvokeAsync("GetAppWishList", new object[] {
                        pAppID,
                        pENVIRONMENT}, this.GetAppWishListOperationCompleted, userState);
        }
        
        private void OnGetAppWishListOperationCompleted(object arg) {
            if ((this.GetAppWishListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppWishListCompleted(this, new GetAppWishListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/CloseAppWishItem", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CloseAppWishItem(int pAppID, long pWishID, string[] pENVIRONMENT) {
            object[] results = this.Invoke("CloseAppWishItem", new object[] {
                        pAppID,
                        pWishID,
                        pENVIRONMENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CloseAppWishItemAsync(int pAppID, long pWishID, string[] pENVIRONMENT) {
            this.CloseAppWishItemAsync(pAppID, pWishID, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void CloseAppWishItemAsync(int pAppID, long pWishID, string[] pENVIRONMENT, object userState) {
            if ((this.CloseAppWishItemOperationCompleted == null)) {
                this.CloseAppWishItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseAppWishItemOperationCompleted);
            }
            this.InvokeAsync("CloseAppWishItem", new object[] {
                        pAppID,
                        pWishID,
                        pENVIRONMENT}, this.CloseAppWishItemOperationCompleted, userState);
        }
        
        private void OnCloseAppWishItemOperationCompleted(object arg) {
            if ((this.CloseAppWishItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseAppWishItemCompleted(this, new CloseAppWishItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/SaveAppWishItem", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveAppWishItem(int pAppID, long pWishID, int pWishType, string pWishNote, string[] pENVIRONMENT) {
            object[] results = this.Invoke("SaveAppWishItem", new object[] {
                        pAppID,
                        pWishID,
                        pWishType,
                        pWishNote,
                        pENVIRONMENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAppWishItemAsync(int pAppID, long pWishID, int pWishType, string pWishNote, string[] pENVIRONMENT) {
            this.SaveAppWishItemAsync(pAppID, pWishID, pWishType, pWishNote, pENVIRONMENT, null);
        }
        
        /// <remarks/>
        public void SaveAppWishItemAsync(int pAppID, long pWishID, int pWishType, string pWishNote, string[] pENVIRONMENT, object userState) {
            if ((this.SaveAppWishItemOperationCompleted == null)) {
                this.SaveAppWishItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAppWishItemOperationCompleted);
            }
            this.InvokeAsync("SaveAppWishItem", new object[] {
                        pAppID,
                        pWishID,
                        pWishType,
                        pWishNote,
                        pENVIRONMENT}, this.SaveAppWishItemOperationCompleted, userState);
        }
        
        private void OnSaveAppWishItemOperationCompleted(object arg) {
            if ((this.SaveAppWishItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAppWishItemCompleted(this, new SaveAppWishItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetSeqId", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetSeqId(string pSeq) {
            object[] results = this.Invoke("GetSeqId", new object[] {
                        pSeq});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeqIdAsync(string pSeq) {
            this.GetSeqIdAsync(pSeq, null);
        }
        
        /// <remarks/>
        public void GetSeqIdAsync(string pSeq, object userState) {
            if ((this.GetSeqIdOperationCompleted == null)) {
                this.GetSeqIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeqIdOperationCompleted);
            }
            this.InvokeAsync("GetSeqId", new object[] {
                        pSeq}, this.GetSeqIdOperationCompleted, userState);
        }
        
        private void OnGetSeqIdOperationCompleted(object arg) {
            if ((this.GetSeqIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeqIdCompleted(this, new GetSeqIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppUsage", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppUsage(string pAppName, System.DateTime pFromDate) {
            object[] results = this.Invoke("GetAppUsage", new object[] {
                        pAppName,
                        pFromDate});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppUsageAsync(string pAppName, System.DateTime pFromDate) {
            this.GetAppUsageAsync(pAppName, pFromDate, null);
        }
        
        /// <remarks/>
        public void GetAppUsageAsync(string pAppName, System.DateTime pFromDate, object userState) {
            if ((this.GetAppUsageOperationCompleted == null)) {
                this.GetAppUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppUsageOperationCompleted);
            }
            this.InvokeAsync("GetAppUsage", new object[] {
                        pAppName,
                        pFromDate}, this.GetAppUsageOperationCompleted, userState);
        }
        
        private void OnGetAppUsageOperationCompleted(object arg) {
            if ((this.GetAppUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppUsageCompleted(this, new GetAppUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppSupport", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppSupport(int pUserSeqID, int pYear) {
            object[] results = this.Invoke("GetAppSupport", new object[] {
                        pUserSeqID,
                        pYear});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppSupportAsync(int pUserSeqID, int pYear) {
            this.GetAppSupportAsync(pUserSeqID, pYear, null);
        }
        
        /// <remarks/>
        public void GetAppSupportAsync(int pUserSeqID, int pYear, object userState) {
            if ((this.GetAppSupportOperationCompleted == null)) {
                this.GetAppSupportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppSupportOperationCompleted);
            }
            this.InvokeAsync("GetAppSupport", new object[] {
                        pUserSeqID,
                        pYear}, this.GetAppSupportOperationCompleted, userState);
        }
        
        private void OnGetAppSupportOperationCompleted(object arg) {
            if ((this.GetAppSupportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppSupportCompleted(this, new GetAppSupportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppSupportDetails", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppSupportDetails(int pUserSeqID, int pYear, string pApp) {
            object[] results = this.Invoke("GetAppSupportDetails", new object[] {
                        pUserSeqID,
                        pYear,
                        pApp});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppSupportDetailsAsync(int pUserSeqID, int pYear, string pApp) {
            this.GetAppSupportDetailsAsync(pUserSeqID, pYear, pApp, null);
        }
        
        /// <remarks/>
        public void GetAppSupportDetailsAsync(int pUserSeqID, int pYear, string pApp, object userState) {
            if ((this.GetAppSupportDetailsOperationCompleted == null)) {
                this.GetAppSupportDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppSupportDetailsOperationCompleted);
            }
            this.InvokeAsync("GetAppSupportDetails", new object[] {
                        pUserSeqID,
                        pYear,
                        pApp}, this.GetAppSupportDetailsOperationCompleted, userState);
        }
        
        private void OnGetAppSupportDetailsOperationCompleted(object arg) {
            if ((this.GetAppSupportDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppSupportDetailsCompleted(this, new GetAppSupportDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gpjws.gpjco.com/GPJ_AppAudit/GetAppSupportByMonth", RequestNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", ResponseNamespace="https://gpjws.gpjco.com/GPJ_AppAudit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppSupportByMonth(int pUserSeqID, int pYear) {
            object[] results = this.Invoke("GetAppSupportByMonth", new object[] {
                        pUserSeqID,
                        pYear});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppSupportByMonthAsync(int pUserSeqID, int pYear) {
            this.GetAppSupportByMonthAsync(pUserSeqID, pYear, null);
        }
        
        /// <remarks/>
        public void GetAppSupportByMonthAsync(int pUserSeqID, int pYear, object userState) {
            if ((this.GetAppSupportByMonthOperationCompleted == null)) {
                this.GetAppSupportByMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppSupportByMonthOperationCompleted);
            }
            this.InvokeAsync("GetAppSupportByMonth", new object[] {
                        pUserSeqID,
                        pYear}, this.GetAppSupportByMonthOperationCompleted, userState);
        }
        
        private void OnGetAppSupportByMonthOperationCompleted(object arg) {
            if ((this.GetAppSupportByMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppSupportByMonthCompleted(this, new GetAppSupportByMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveUserDataCompletedEventHandler(object sender, SaveUserDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUserDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUserDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AppWishListLikeCompletedEventHandler(object sender, AppWishListLikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppWishListLikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppWishListLikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppWishListCountCompletedEventHandler(object sender, GetAppWishListCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppWishListCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppWishListCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppWishListCompletedEventHandler(object sender, GetAppWishListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppWishListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppWishListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CloseAppWishItemCompletedEventHandler(object sender, CloseAppWishItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseAppWishItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseAppWishItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveAppWishItemCompletedEventHandler(object sender, SaveAppWishItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAppWishItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAppWishItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSeqIdCompletedEventHandler(object sender, GetSeqIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeqIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeqIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppUsageCompletedEventHandler(object sender, GetAppUsageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppSupportCompletedEventHandler(object sender, GetAppSupportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppSupportDetailsCompletedEventHandler(object sender, GetAppSupportDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppSupportDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppSupportDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppSupportByMonthCompletedEventHandler(object sender, GetAppSupportByMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppSupportByMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppSupportByMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591